from pathlib import Path
from docx import Document
from docx.oxml import OxmlElement

SRC = Path(r"C:\Users\Admin\Documents\Obsidian\SGU\Fourth year\Research Proposal\De_cuong_nghien_cuu_NSGAII_Ride_Hailing.docx")
OUT = Path(r"C:\Users\Admin\Documents\Obsidian\SGU\Fourth year\Research Proposal\.docx_qa\section9_detailed.docx")

def insert_before(anchor, text, style_name="Normal"):
    marker = OxmlElement("w:p")
    anchor._p.addprevious(marker)
    p = anchor._parent.add_paragraph()
    p._p.getparent().remove(p._p)
    marker.getparent().replace(marker, p._p)
    p.style = style_name
    p.add_run(text)

doc = Document(SRC)
paras = doc.paragraphs
start = next(i for i, p in enumerate(paras) if p.text.strip().startswith("9. DỰ KIẾN NỘI DUNG"))
end = next(i for i, p in enumerate(paras) if p.text.strip().startswith("10. DANH MỤC TÀI LIỆU"))
anchor = paras[end]
for p in paras[start + 1:end]:
    p._element.getparent().remove(p._element)

outline = [
    ("Normal", "Nội dung đồ án dự kiến gồm ba chương chính và phần kết luận. Các chương được tổ chức theo trình tự từ cơ sở lý thuyết và tổng quan nghiên cứu, xây dựng mô hình và đề xuất thuật toán, đến cài đặt thực nghiệm, đánh giá kết quả và thảo luận."),
    ("Heading 2", "CHƯƠNG 1. TỔNG QUAN VỀ BÀI TOÁN ĐIỀU PHỐI GỌI XE ĐA MỤC TIÊU THEO CƠ CHẾ BATCHING"),
    ("Normal", "1.1. Giới thiệu tổng quan về hệ thống gọi xe công nghệ"),
    ("Normal", "1.1.1. Khái niệm và đặc điểm của dịch vụ gọi xe công nghệ"),
    ("Normal", "1.1.2. Các thành phần cơ bản của hệ thống: hành khách, tài xế, phương tiện và nền tảng điều phối"),
    ("Normal", "1.1.3. Quy trình phát sinh yêu cầu, tìm kiếm tài xế, phân công và hoàn thành cuốc xe"),
    ("Normal", "1.1.4. Các yêu cầu vận hành: thời gian phản hồi, tỷ lệ phục vụ, quãng đường chạy rỗng và khả năng mở rộng"),
    ("Normal", "1.1.5. Các vấn đề về hiệu quả và công bằng trong hoạt động phân công cuốc xe"),
    ("Normal", "1.2. Tổng quan về bài toán điều phối và ghép nối gọi xe"),
    ("Normal", "1.2.1. Phát biểu bài toán ghép nối giữa tập tài xế và tập yêu cầu"),
    ("Normal", "1.2.2. Mô hình đồ thị hai phía và bài toán phân công"),
    ("Normal", "1.2.3. Điều phối tức thời và hạn chế của quy tắc tài xế gần nhất"),
    ("Normal", "1.2.4. Điều phối động khi yêu cầu và trạng thái tài xế thay đổi theo thời gian"),
    ("Normal", "1.2.5. Các ràng buộc thực tế: tính duy nhất, sức chứa và thời gian đến điểm đón"),
    ("Normal", "1.3. Cơ chế Batching trong điều phối gọi xe"),
    ("Normal", "1.3.1. Khái niệm Batch và cửa sổ gom yêu cầu"),
    ("Normal", "1.3.2. Quy trình thu thập yêu cầu và tài xế khả dụng trong từng Batch"),
    ("Normal", "1.3.3. Cơ chế cập nhật trạng thái tài xế và yêu cầu qua nhiều Batch liên tiếp"),
    ("Normal", "1.3.4. Sự đánh đổi giữa độ dài Batch, chất lượng ghép nối và độ trễ quyết định"),
    ("Normal", "1.3.5. Ưu điểm, hạn chế và phạm vi áp dụng của cơ chế Batching"),
    ("Normal", "1.4. Cơ sở toán học của bài toán tối ưu đa mục tiêu"),
    ("Normal", "1.4.1. Khái niệm bài toán tối ưu tổ hợp và không gian nghiệm rời rạc"),
    ("Normal", "1.4.2. Bài toán tối ưu đơn mục tiêu và bài toán tối ưu đa mục tiêu"),
    ("Normal", "1.4.3. Quan hệ trội Pareto và tính chất của nghiệm không trội"),
    ("Normal", "1.4.4. Biên Pareto, tập Pareto và ý nghĩa của sự đa dạng nghiệm"),
    ("Normal", "1.4.5. Các phương pháp lựa chọn một phương án vận hành từ tập nghiệm Pareto"),
    ("Normal", "1.4.6. Các chỉ số đánh giá chất lượng tập nghiệm đa mục tiêu"),
    ("Normal", "1.5. Thuật toán tiến hóa đa mục tiêu và NSGA-II"),
    ("Normal", "1.5.1. Tổng quan về thuật toán tiến hóa và biểu diễn quần thể nghiệm"),
    ("Normal", "1.5.2. Nguyên lý xếp hạng không trội nhanh"),
    ("Normal", "1.5.3. Khoảng cách mật độ và cơ chế duy trì tính đa dạng"),
    ("Normal", "1.5.4. Cơ chế ưu tú và lựa chọn trong NSGA-II"),
    ("Normal", "1.5.5. Các toán tử lai ghép, đột biến và sửa nghiệm"),
    ("Normal", "1.5.6. Ưu điểm và hạn chế của NSGA-II đối với bài toán điều phối theo Batch"),
    ("Normal", "1.6. Công bằng trong bài toán phân công cuốc xe"),
    ("Normal", "1.6.1. Các đối tượng và quan điểm công bằng trong hệ thống gọi xe"),
    ("Normal", "1.6.2. Công bằng dựa trên thu nhập, số cuốc, tỷ lệ phục vụ và cơ hội nhận cuốc"),
    ("Normal", "1.6.3. Khái niệm tài xế đủ điều kiện và cách xác định một cơ hội nhận cuốc"),
    ("Normal", "1.6.4. Tỷ lệ tiếp cận cuốc và độ lệch chuẩn tỷ lệ tiếp cận cuốc"),
    ("Normal", "1.6.5. Mối quan hệ giữa công bằng theo cơ hội và hiệu quả vận hành"),
    ("Normal", "1.6.6. Vai trò của thu nhập như một chỉ số đánh giá bổ trợ"),
    ("Normal", "1.7. Khảo sát các hướng tiếp cận giải bài toán điều phối gọi xe"),
    ("Normal", "1.7.1. Phương pháp tham lam dựa trên khoảng cách hoặc thời gian đến điểm đón"),
    ("Normal", "1.7.2. Phương pháp tối ưu toán học và bài toán phân công tuyến tính"),
    ("Normal", "1.7.3. Các phương pháp Heuristic và Metaheuristic"),
    ("Normal", "1.7.4. Phương pháp học tăng cường và học máy trong điều phối gọi xe"),
    ("Normal", "1.7.5. Các nghiên cứu quốc tế về điều phối có xét yếu tố công bằng"),
    ("Normal", "1.7.6. Các nghiên cứu và ứng dụng liên quan tại Việt Nam"),
    ("Normal", "1.7.7. So sánh ưu điểm, hạn chế và điều kiện áp dụng của các nhóm phương pháp"),
    ("Normal", "1.8. Khảo sát các bộ dữ liệu thực nghiệm chuẩn và công khai"),
    ("Normal", "1.8.1. Bộ dữ liệu NYC Taxi: phạm vi, cấu trúc và các trường thông tin"),
    ("Normal", "1.8.2. Bộ dữ liệu RideAustin: phạm vi, cấu trúc và các trường thông tin"),
    ("Normal", "1.8.3. Khả năng xây dựng luồng yêu cầu và trạng thái tài xế từ dữ liệu hành trình"),
    ("Normal", "1.8.4. Khả năng xác định số hành khách và sức chứa phương tiện"),
    ("Normal", "1.8.5. Tiêu chí lựa chọn bộ dữ liệu chính thức cho thực nghiệm"),
    ("Normal", "1.8.6. Các hạn chế dữ liệu và phương án tiền xử lý"),
    ("Normal", "1.9. Tiêu chí đánh giá chất lượng thuật toán"),
    ("Normal", "1.9.1. Tổng quãng đường chạy rỗng và thời gian đến điểm đón"),
    ("Normal", "1.9.2. Thời gian chờ trung bình và tỷ lệ yêu cầu được phục vụ"),
    ("Normal", "1.9.3. Độ lệch chuẩn tỷ lệ tiếp cận cuốc và phân phối số cuốc giữa các tài xế"),
    ("Normal", "1.9.4. Thời gian tính toán mỗi Batch và tỷ lệ Batch đáp ứng giới hạn thời gian"),
    ("Normal", "1.9.5. Tỷ lệ nghiệm khả thi và mức độ vi phạm ràng buộc"),
    ("Normal", "1.9.6. Chất lượng, độ hội tụ và độ phân tán của tập nghiệm Pareto"),
    ("Normal", "1.9.7. Thu nhập tích lũy và độ lệch thu nhập như các chỉ số kiểm tra bổ trợ"),
    ("Normal", "1.10. Khoảng trống nghiên cứu và định hướng của đề tài"),
    ("Normal", "1.10.1. Những hạn chế của các nghiên cứu và phương pháp hiện có"),
    ("Normal", "1.10.2. Nhu cầu kết hợp Batching, NSGA-II và công bằng theo cơ hội nhận cuốc"),
    ("Normal", "1.10.3. Vấn đề nghiên cứu, câu hỏi nghiên cứu và phạm vi giải quyết của đề tài"),
    ("Normal", "1.10.4. Các đóng góp dự kiến về mô hình, thuật toán và thực nghiệm"),
    ("Normal", "1.11. Tóm tắt chương 1"),
    ("Heading 2", "CHƯƠNG 2. ĐỀ XUẤT THUẬT TOÁN NSGA-II CHO BÀI TOÁN ĐIỀU PHỐI GỌI XE THEO BATCH"),
    ("Normal", "2.1. Phát biểu bài toán và các giả định nghiên cứu"),
    ("Normal", "2.1.1. Mô tả đầu vào, đầu ra và chu kỳ ra quyết định"),
    ("Normal", "2.1.2. Tập tài xế, tập yêu cầu và trạng thái hệ thống"),
    ("Normal", "2.1.3. Các giả định về thời gian di chuyển, hủy chuyến và cập nhật trạng thái"),
    ("Normal", "2.1.4. Phạm vi ghép một tài xế với tối đa một yêu cầu trong mỗi Batch"),
    ("Normal", "2.1.5. Xác định các cặp ghép khả thi trước khi tối ưu"),
    ("Normal", "2.2. Mô hình vận hành theo nhiều Batch liên tiếp"),
    ("Normal", "2.2.1. Phân chia dòng yêu cầu theo cửa sổ thời gian"),
    ("Normal", "2.2.2. Thu thập tài xế sẵn sàng và yêu cầu đang mở"),
    ("Normal", "2.2.3. Tạo ma trận khoảng cách và ma trận cặp ghép khả thi"),
    ("Normal", "2.2.4. Thực hiện quyết định điều phối và cập nhật hệ thống"),
    ("Normal", "2.2.5. Xử lý yêu cầu chưa được phục vụ sau mỗi Batch"),
    ("Normal", "2.3. Xây dựng mô hình toán học đa mục tiêu"),
    ("Normal", "2.3.1. Ký hiệu, tập hợp, tham số và biến quyết định"),
    ("Normal", "2.3.2. Hàm mục tiêu tối thiểu hóa tổng quãng đường chạy rỗng"),
    ("Normal", "2.3.3. Xác định số cơ hội nhận cuốc và tỷ lệ tiếp cận cuốc của tài xế"),
    ("Normal", "2.3.4. Hàm mục tiêu tối thiểu hóa độ lệch chuẩn tỷ lệ tiếp cận cuốc"),
    ("Normal", "2.3.5. Ràng buộc mỗi yêu cầu được gán cho tối đa một tài xế"),
    ("Normal", "2.3.6. Ràng buộc mỗi tài xế nhận tối đa một yêu cầu trong một Batch"),
    ("Normal", "2.3.7. Ràng buộc sức chứa theo số hành khách và loại phương tiện"),
    ("Normal", "2.3.8. Ràng buộc giới hạn thời gian đến điểm đón"),
    ("Normal", "2.3.9. Điều kiện miền giá trị của biến quyết định"),
    ("Normal", "2.3.10. Phân tích tính khả thi và mối quan hệ giữa hai hàm mục tiêu"),
    ("Normal", "2.4. Cấu trúc tổng thể của phương pháp NSGA-II đề xuất"),
    ("Normal", "2.4.1. Sơ đồ quy trình của thuật toán trong một Batch"),
    ("Normal", "2.4.2. Luồng dữ liệu giữa mô-đun mô phỏng và mô-đun tối ưu"),
    ("Normal", "2.4.3. Cơ chế lặp qua các Batch và lưu trạng thái lịch sử"),
    ("Normal", "2.4.4. Điều kiện dừng và đầu ra của thuật toán"),
    ("Normal", "2.5. Thiết kế biểu diễn nghiệm và khởi tạo quần thể"),
    ("Normal", "2.5.1. Mã hóa nhiễm sắc thể bằng vector số nguyên"),
    ("Normal", "2.5.2. Ý nghĩa của gen và cách biểu diễn yêu cầu chưa được phục vụ"),
    ("Normal", "2.5.3. Phương pháp khởi tạo nghiệm ngẫu nhiên khả thi"),
    ("Normal", "2.5.4. Phương pháp gieo nghiệm dựa trên Heuristic khoảng cách"),
    ("Normal", "2.5.5. Cơ chế duy trì tính đa dạng của quần thể ban đầu"),
    ("Normal", "2.6. Xây dựng hàm đánh giá và xếp hạng nghiệm"),
    ("Normal", "2.6.1. Tính toán giá trị hai hàm mục tiêu"),
    ("Normal", "2.6.2. Kiểm tra tính khả thi và xử lý vi phạm ràng buộc"),
    ("Normal", "2.6.3. Xếp hạng không trội nhanh"),
    ("Normal", "2.6.4. Tính khoảng cách mật độ"),
    ("Normal", "2.6.5. Cơ chế so sánh hai nghiệm trong lựa chọn giải đấu"),
    ("Normal", "2.7. Thiết kế các toán tử tiến hóa và cơ chế sửa nghiệm"),
    ("Normal", "2.7.1. Toán tử lựa chọn giải đấu nhị phân"),
    ("Normal", "2.7.2. Toán tử lai ghép phù hợp với mã hóa số nguyên"),
    ("Normal", "2.7.3. Toán tử đột biến hoán vị và thay đổi phép gán"),
    ("Normal", "2.7.4. Sửa lỗi gán trùng tài xế"),
    ("Normal", "2.7.5. Loại bỏ cặp ghép vi phạm ràng buộc sức chứa"),
    ("Normal", "2.7.6. Loại bỏ cặp ghép vi phạm giới hạn thời gian đến điểm đón"),
    ("Normal", "2.7.7. Tái phân công yêu cầu bằng tài xế còn rảnh và khả thi"),
    ("Normal", "2.8. Lựa chọn phương án điều phối từ tập nghiệm Pareto"),
    ("Normal", "2.8.1. Phương pháp chọn điểm gối của biên Pareto"),
    ("Normal", "2.8.2. Phương pháp lựa chọn theo ngưỡng chất lượng dịch vụ"),
    ("Normal", "2.8.3. Chuẩn hóa các mục tiêu trước khi ra quyết định"),
    ("Normal", "2.8.4. Quy tắc phá hòa và bảo đảm tính tái lập"),
    ("Normal", "2.9. Mã giả và phân tích lý thuyết thuật toán đề xuất"),
    ("Normal", "2.9.1. Mã giả quy trình điều phối theo Batch"),
    ("Normal", "2.9.2. Mã giả thuật toán NSGA-II và cơ chế sửa nghiệm"),
    ("Normal", "2.9.3. Phân tích độ phức tạp thời gian"),
    ("Normal", "2.9.4. Phân tích độ phức tạp không gian"),
    ("Normal", "2.9.5. Phân tích khả năng đáp ứng giới hạn thời gian của Batch"),
    ("Normal", "2.10. Xây dựng phương pháp đối chứng Greedy"),
    ("Normal", "2.10.1. Quy tắc chọn tài xế khả thi gần điểm đón nhất"),
    ("Normal", "2.10.2. Cách xử lý ràng buộc sức chứa và cửa sổ thời gian"),
    ("Normal", "2.10.3. Cách xử lý yêu cầu chưa được phục vụ"),
    ("Normal", "2.10.4. Bảo đảm điều kiện so sánh công bằng giữa Greedy và NSGA-II"),
    ("Normal", "2.11. Tóm tắt chương 2"),
    ("Heading 2", "CHƯƠNG 3. CÀI ĐẶT THỰC NGHIỆM, ĐÁNH GIÁ KẾT QUẢ VÀ THẢO LUẬN"),
    ("Normal", "3.1. Thiết lập môi trường cài đặt và thực nghiệm"),
    ("Normal", "3.1.1. Cấu hình phần cứng và hệ điều hành"),
    ("Normal", "3.1.2. Ngôn ngữ lập trình, thư viện và công cụ phát triển"),
    ("Normal", "3.1.3. Cấu trúc chương trình và các mô-đun chính"),
    ("Normal", "3.1.4. Cơ chế ghi log, lưu kết quả và tái lập thực nghiệm"),
    ("Normal", "3.2. Chuẩn bị dữ liệu thực nghiệm"),
    ("Normal", "3.2.1. Mô tả chi tiết bộ dữ liệu được lựa chọn"),
    ("Normal", "3.2.2. Làm sạch dữ liệu thời gian và tọa độ hành trình"),
    ("Normal", "3.2.3. Xây dựng yêu cầu đặt xe và trạng thái ban đầu của tài xế"),
    ("Normal", "3.2.4. Xử lý số lượng hành khách và sức chứa phương tiện"),
    ("Normal", "3.2.5. Chia tập phát triển, tập hiệu chỉnh và tập đánh giá cuối"),
    ("Normal", "3.3. Thiết kế kịch bản và giao thức thực nghiệm"),
    ("Normal", "3.3.1. Kịch bản giờ cao điểm và giờ thấp điểm"),
    ("Normal", "3.3.2. Kịch bản thay đổi mật độ yêu cầu và số lượng tài xế"),
    ("Normal", "3.3.3. Kịch bản thay đổi độ dài Batch"),
    ("Normal", "3.3.4. Kịch bản thay đổi cơ cấu xe máy, ô tô và số hành khách"),
    ("Normal", "3.3.5. Thiết lập tham số NSGA-II"),
    ("Normal", "3.3.6. Số lần chạy, hạt giống ngẫu nhiên và phương pháp tổng hợp kết quả"),
    ("Normal", "3.3.7. Tiêu chuẩn kiểm tra và báo cáo thời gian tính toán"),
    ("Normal", "3.4. Các thuật toán và cấu hình đối sánh"),
    ("Normal", "3.4.1. Thuật toán Greedy chọn tài xế gần nhất"),
    ("Normal", "3.4.2. NSGA-II không sử dụng cơ chế sửa nghiệm"),
    ("Normal", "3.4.3. NSGA-II đầy đủ với cơ chế sửa nghiệm đề xuất"),
    ("Normal", "3.4.4. Nguyên tắc sử dụng cùng dữ liệu, ràng buộc và ngân sách tính toán"),
    ("Normal", "3.5. Kết quả về hiệu quả vận hành và chất lượng dịch vụ"),
    ("Normal", "3.5.1. So sánh tổng quãng đường chạy rỗng"),
    ("Normal", "3.5.2. So sánh thời gian đến điểm đón và thời gian chờ"),
    ("Normal", "3.5.3. So sánh tỷ lệ yêu cầu được phục vụ"),
    ("Normal", "3.5.4. So sánh kết quả giữa kịch bản cao điểm và thấp điểm"),
    ("Normal", "3.5.5. Đánh giá ảnh hưởng của ràng buộc sức chứa đến khả năng phục vụ"),
    ("Normal", "3.6. Kết quả về công bằng theo cơ hội nhận cuốc"),
    ("Normal", "3.6.1. So sánh độ lệch chuẩn tỷ lệ tiếp cận cuốc"),
    ("Normal", "3.6.2. So sánh phân phối số cuốc giữa các tài xế"),
    ("Normal", "3.6.3. Phân tích nhóm tài xế có ít và nhiều cơ hội khả thi"),
    ("Normal", "3.6.4. Kiểm tra mối quan hệ giữa công bằng theo cơ hội và phân phối thu nhập"),
    ("Normal", "3.6.5. Phân tích sự đánh đổi giữa công bằng và quãng đường chạy rỗng"),
    ("Normal", "3.7. Đánh giá chất lượng tập nghiệm Pareto và hiệu năng thuật toán"),
    ("Normal", "3.7.1. Minh họa biên Pareto trong các kịch bản đại diện"),
    ("Normal", "3.7.2. Đánh giá độ hội tụ và độ phân tán của tập nghiệm"),
    ("Normal", "3.7.3. Đánh giá tỷ lệ nghiệm khả thi"),
    ("Normal", "3.7.4. Đánh giá thời gian tính toán mỗi Batch"),
    ("Normal", "3.7.5. Đánh giá khả năng đáp ứng thời gian thực"),
    ("Normal", "3.7.6. Phân tích độ ổn định qua nhiều lần chạy"),
    ("Normal", "3.8. Phân tích độ nhạy và thí nghiệm loại bỏ thành phần"),
    ("Normal", "3.8.1. Ảnh hưởng của kích thước quần thể"),
    ("Normal", "3.8.2. Ảnh hưởng của số thế hệ"),
    ("Normal", "3.8.3. Ảnh hưởng của xác suất lai ghép và đột biến"),
    ("Normal", "3.8.4. Ảnh hưởng của độ dài Batch"),
    ("Normal", "3.8.5. Vai trò của khởi tạo Heuristic"),
    ("Normal", "3.8.6. Vai trò của cơ chế sửa nghiệm"),
    ("Normal", "3.8.7. Ảnh hưởng của quy tắc lựa chọn nghiệm từ tập Pareto"),
    ("Normal", "3.9. Bàn luận và phân tích kết quả"),
    ("Normal", "3.9.1. Giải thích nguyên nhân NSGA-II tốt hơn hoặc kém hơn Greedy trong từng trường hợp"),
    ("Normal", "3.9.2. Phân tích ý nghĩa vận hành của các phương án trên biên Pareto"),
    ("Normal", "3.9.3. Đề xuất cách lựa chọn phương án điều phối phù hợp với mục tiêu hệ thống"),
    ("Normal", "3.9.4. Đóng góp thực nghiệm và các phân tích mang dấu ấn cá nhân"),
    ("Normal", "3.9.5. Khả năng áp dụng phương pháp trong hệ thống gọi xe thực tế"),
    ("Normal", "3.10. Hạn chế và các nguy cơ ảnh hưởng đến tính hợp lệ"),
    ("Normal", "3.10.1. Hạn chế của bộ dữ liệu và cách tái dựng trạng thái tài xế"),
    ("Normal", "3.10.2. Hạn chế của giả định thời gian di chuyển"),
    ("Normal", "3.10.3. Hạn chế của mô hình ghép một tài xế - một yêu cầu trong mỗi Batch"),
    ("Normal", "3.10.4. Hạn chế về khả năng khái quát kết quả"),
    ("Normal", "3.10.5. Các biện pháp giảm thiểu sai lệch trong thực nghiệm"),
    ("Normal", "3.11. Tóm tắt chương 3"),
    ("Heading 2", "KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN"),
    ("Normal", "1. Tổng hợp các kết quả đạt được so với mục tiêu và câu hỏi nghiên cứu"),
    ("Normal", "2. Tóm tắt đóng góp về mô hình toán học, thuật toán và quy trình thực nghiệm"),
    ("Normal", "3. Đánh giá mức độ đáp ứng các giả thuyết nghiên cứu"),
    ("Normal", "4. Những hạn chế còn tồn tại của đồ án"),
    ("Normal", "5. Hướng phát triển về đi chung xe và điều phối chuỗi nhiều yêu cầu"),
    ("Normal", "6. Hướng phát triển về dữ liệu giao thông thời gian thực và dự báo nhu cầu"),
    ("Normal", "7. Hướng phát triển về các thuật toán đa mục tiêu và cơ chế công bằng khác"),
]

for style, text in outline:
    insert_before(anchor, text, style)
OUT.parent.mkdir(parents=True, exist_ok=True)
doc.save(OUT)
print(OUT)
